# ==============================================================================
# Production-Grade Comprehensive Alias Catalog (+100 Definitions)
# ==============================================================================

# --- Modern Core Shell Commands ---
alias ls="eza --icons --group-directories-first"
alias ll="eza -lh --icons --group-directories-first"
alias la="eza -lah --icons --group-directories-first"
alias lt="eza --tree --level=2 --icons"
alias cat="bat --style=plain"
alias grep="ripgrep"
alias find="fd"
alias du="dust"
alias df="dua i"
alias top="btop"
alias htop="htop"

# --- Arch Linux & Package Management (Pacman / AUR) ---
alias pacin="sudo pacman -S --needed"
alias pacupd="sudo pacman -Syu"
alias pacrm="sudo pacman -Rns"
alias paccl="sudo pacman -Scc"
alias pacq="pacman -Qi"
alias pacsearch="pacman -Ss"
alias yains="yay -S --needed"
alias yayupd="yay -Syu"
alias parins="paru -S --needed"
alias parupd="paru -Syu"

# --- Ruby on Rails & Bundler Infrastructure ---
alias rc="bundle exec rails console"
alias rs="bundle exec rails server"
alias rg="bundle exec rails generate"
alias rd="bundle exec rails destroy"
alias rdb="bundle exec rails dbconsole"
alias rdm="bundle exec rails db:migrate"
alias rdr="bundle exec rails db:rollback"
alias rds="bundle exec rails db:setup"
alias rdc="bundle exec rails db:create"
alias rdd="bundle exec rails db:drop"
alias rdt="bundle exec rails db:test:prepare"
alias rdseed="bundle exec rails db:seed"
alias rroutes="bundle exec rails routes"
alias rlog="tail -f log/development.log"
alias rtest="bundle exec rails test"
alias rspec="bundle exec rspec"
alias b="bundle exec"
alias bi="bundle install"
alias bu="bundle update"
alias bo="bundle outdated"

# --- Git Operational Workflow ---
alias g="git"
alias gs="git status -sb"
alias ga="git add"
alias gaa="git add --all"
alias gc="git commit -v"
alias gcm="git commit -m"
alias gca="git commit -v --amend"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gd="git diff"
alias gds="git diff --staged"
alias gl="git log --oneline --graph --decorate"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias gpl="git pull"
alias gf="git fetch"
alias grb="git rebase"
alias grba="git rebase --abort"
alias grbc="git rebase --continue"
alias gst="git stash"
alias gstp="git stash pop"

# --- Docker & Docker Compose Operations ---
alias d="docker"
alias dc="docker-compose"
alias dps="docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'"
alias dpa="docker ps -a"
alias di="docker images"
alias dlog="docker logs -f"
alias dx="docker exec -it"
alias dcup="docker-compose up -d"
alias dcdown="docker-compose down"
alias dclog="docker-compose logs -f"
alias dcbuild="docker-compose build"
alias dcr="docker-compose run --rm"

# --- Kubernetes Controls ---
alias k="kubectl"
alias kgp="kubectl get pods"
alias kgs="kubectl get services"
alias kgd="kubectl get deployments"
alias kdp="kubectl describe pod"
alias kl="kubectl logs -f"
alias kex="kubectl exec -it"

# --- Terminal Text Editors & Multi-terminal Utilities ---
alias v="nvim"
alias nv="nvim"
alias lz="lazygit"
alias ghc="gh pr checkout"
alias t="tmux"
alias ta="tmux attach -t"
alias tls="tmux ls"
alias tkill="tmux kill-session -t"

# --- System & Network Diagnostics ---
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias clear="clear && printf '\e[3J'"
alias ipb="curl ifconfig.me"
alias openports="ss -tulanp"
alias reload="exec zsh"